---
Author: Prerana Patil
Title: Framework for Effective Visualizations
---

# Introduction

In this information age, descriptive analytics and presentation are one of the main components for the success of businesses. More and more businesses are now moving towards presenting data in a way that is clear and drives a point. Hence, creating smart visualizations is no longer a 'nice-to-have' skill but a 'must-have' skill for managers.

The main reason for this shift is the easy availability of data. However, data visualization is not just about displaying data, it is about presenting data in a way that is easy to understand and comprehend. The job of the creator is to make a visualization that connects with the reader.

Also, bad visualizations can not only create misunderstandings but could lead to wrong conclusions and have an adverse impact on businesses.


## What makes an effective visualization?

While each visualization is designed for a unique purpose for different audiences and with different data, there are certain guidelines that can be followed to evaluate if visualization is effective or not. Visualizations can be a powerful tool if done right. Good visualizations present data in a way that it is easy to understand relations or correlation between various factors and detect patterns that emerge over time. 

Here are some guidelines that can be used to evaluate if visualization is effective or not. If visualizations have these characteristics, people can use it on a regular basis as they are comprehensible and easy to use and understand.


### Evaluation Criteria for an effective visualization:

##### **1. Tells a story**

At first glance, data is just numbers. The sheer volume of today's data makes it very difficult to comprehend. This data needs to be analyzed and presented in a format that is easy for the reader to understand. Data generally represent people, places, events, etc. but in its raw format, it cannot be understood. Only when this data is converted to visuals that we can establish an emotional, social and cultural connection between data and real life. 

Visualizations with a compelling narrative, tell a story that is memorable to the audience. A story packages information in a format that can be easily remembered. Storytelling helps viewers gain insights from the data. Designers need to dig deep into the data in order to understand it and make the information relevant to the audience. 


##### **2. Is tailored to an audience**

To be meaningful, the presentation of information should be done keeping the audience in mind. The terms and concepts used in the visualizations should be easily understood by the audience for whom the visualization was made. For instance, the language used while developing visuals for sales executives will be different than the ones created for managers. Hence, the context is important. 

For visualizations to be successful, designers need to keep in mind the audience. They have to keep in mind the viewer's expectations and design in a way that the visual is most useful to the viewer. 


##### **3. Has a well-defined aim**

It is also important to understand why visualization is being created. Designers should keep in mind the following questions while creating visualizations: 
  
  * Is the information conceptual or data-driven? 
  
  Conceptual graphs generally focus on ideas. They are designed with an aim to explain to the viewer a certain idea or a concept. Data-driven visuals focus on numbers and hence are specific to a certain event, place or person/persons, etc. Here the information is more quantitative as opposed to conceptual graphs where the information is qualitative. The visual cues, the amount of information, etc. conveyed in both these will be very different from each other.
  
  * Will it be an exploratory analysis or declarative analysis or a combination of these? 

  Exploratory analysis will usually begin with a hypothesis which will be proved or disproved when visuals are created using the data. The goal is to confirm certain assumptions. Exploratory analysis helps users explore data and identify patterns. Declarative analysis is designed for a particular purpose. Visuals created are used to affirm a certain phenomenon. Design choices will depend on the answer to these questions.


##### **4. Sets up a clear design framework**
  
  While creating a visualization, the designer needs to define the semantics and syntax that will be used. Semantics defines the meaning of terms and graphs used and syntax defines the structure of communication. A good data visualization is the one which is understood by everyone. Good visualizations follow certain best practices when it comes to design elements: 

  * Visual Hierarchy
  
  Humans are drawn to information that stands out. Smart designers make use of this to draw attention to information that is most important. Using different font sizes, uniform fonts and colors to depict one information group are common ways to establish visual hierarchy. 
  
  * Captions, Legends, and Annotations
  
  Including proper captions explain graphics is considered good practice, though captions should not be long as it may confuse and irritate the reader. Captions should explain the whole point of the graphic is a clear and concise way. Legends are used to help readers understand which symbols and colors belong to which group. Annotations are used to highlight particular features of a graphic. Captions, legends, and annotations are an important part of any graphics and enhance the quality of the graphic when used well.

  * Less is more
  
  Designers should be careful of chart junk. Before adding any color, illustration, effect, etc. designers should consider if it will improve the overall quality of the visual. Anything that is not necessary or does not add value should be eliminated. 
 
  * Labeling
  
  Labels help readers to read and interpret data but too many or too few can be a problem. It is important to make sure all important information is appropriately labeled. Acronyms that are not widely understood should be avoided. Formatting of labels should be consistent. It is a good practice to keep the chart title clear and concise. 

  * Color
  
  Color plays an important role in visualization readers grab relationships and patterns quickly. Colors can evoke emotional connections and influence how readers understand the data. Also, The font type, font size, and color should be such that it does not interfere but rather enhance the readability of the visual.


### [Evaluation of Five Visualizations](/Visualizations.md)

***

# References  

<div id="div1" style="margin-bottom:15px; ></div>
  1. 5 Characteristics All Excellent Data Visualization Should Have:
     https://ecmapping.com/2016/05/17/5-characteristics-all-excellent-data-visualization-should-have/

<div id="div2" style="margin-bottom:15px;"> </div>

  2. 25 Tips to Instantly Improve Your Data Visualization Design: 
     https://www.columnfivemedia.com/25-tips-to-upgrade-your-data-visualization-design

<div id="div3" style="margin-bottom:15px;"> </div>
     
  3. Harvard Business Review, The Three Elements of Successful Data Visualizations: 
     https://hbr.org/2013/04/the-three-elements-of-successf

<div id="div4" style="margin-bottom:15px;"> </div>
     
  4. Harvard Business Review, Visualizations That Really Work: 
     https://hbr.org/2016/06/visualizations-that-really-work?referral=03759&cm_vc=rr_item_page.bottom

<div id="div5" style="margin-bottom:15px;"> </div>
     
  5. Harvard Business Review, The Quick and Dirty on Data Visualization:
     https://hbr.org/2014/04/the-quick-and-dirty-on-data-visualization?referral=03759&cm_vc=rr_item_page.bottom

<div id="div6" style="margin-bottom:15px;"> </div>
     
  6. What makes a good visualization?
     https://www.e-nor.com/blog/data-visualization/makes-good-visualization

<div id="div7" style="margin-bottom:15px;"> </div>
     
  7. What Makes for Great Data Visualization and Why?
     https://www.datalabsagency.com/2015/05/21/what-makes-for-great-data-visualization/

<div id="div8" style="margin-bottom:15px;"> </div>
     
  8. Handbook of Data Visualization:
     http://haralick.org/DV/Handbook_of_Data_Visualization.pdf

<div id="div9" style="margin-bottom:15px;"> </div>
  
  9. New Thinking on, and with, Data Visualization:
     https://arxiv.org/pdf/1805.11300.pdf

<div id="div10" style="margin-bottom:15px;"> </div>
     
  10. 10 Questions to ask when creating a visualization:
      http://10qviz.org/

<div id="div11" style="margin-bottom:15px;"> </div>
      
  11. Effective Visualization of Multi-Dimensional Data - A Hands-on Approach:
      https://medium.com/swlh/effective-visualization-of-multi-dimensional-data-a-hands-on-approach-b48f36a56ee8

<div id="div12" style="margin-bottom:15px;"> </div>
  12. How To Use Color To Prove Your Point, From A Data Viz Expert:
      https://www.fastcompany.com/3062182/how-to-use-color-to-prove-your-point-from-a-data-viz-expert
  
  
